ValidationService doesn't handle multiple constrains for an input #35
oxygenxml-incubator/oxygen-account pull request #37
Opened 2023-08-09 12:58 UTC by matrex32

2023-08-09 13:06 UTC, matrex32 commented
Closes #35

2023-08-10 10:22 UTC, adrianasbircea requested changes

2023-08-10 10:22 UTC, adrianasbircea commented on oxygen-account/src/test/java/com/oxygenxml/account/user/UserControllerTest.java
> +		.andExpect(jsonPath("$.errors[*].errorMessage", containsInAnyOrder(Message.EMPTY_FIELD.getMessage(), Message.SHORT_FIELD.getMessage(), Message.EMAIL_INVALID.getMessage())))
1. Nu este verificat fieldName-ul din erori.
2. Verificarea erorilor ar trebui sa fie individuala, adica verificam informatiile (message, messageId, fieldName) pentru fiecare eroare in parte. De exemplu, se poate rescrie o parte din asserturi astfel:
```
resultActions.andExpect(jsonPath("$.errors[?(@.fieldName == 'name')].messageId", hasItem(Message.EMPTY_FIELD.getId())));
resultActions.andExpect(jsonPath("$.errors[?(@.fieldName == 'name')].errorMessage", hasItem(Message.EMPTY_FIELD.getMessage())));
```
sau se poate aserta astfel:
```
resultActions.andExpect(jsonPath("$.errors.[0].fieldName", is("name")));
resultActions.andExpect(jsonPath("$.errors.[0].messageId", is(Message.EMPTY_FIELD.getId())));
resultActions.andExpect(jsonPath("$.errors.[0].errorMessage", is(Message.EMPTY_FIELD.getMessage())));
```
La fel se continua cu asserturile si pentru celelalte fielduri care au erori.

2023-08-10 16:10 UTC, adrianasbircea approved these changes

2023-08-10 16:11 UTC, adrianasbircea approved these changes

2023-08-11 07:07 UTC, merged