#49 delete funtionality
oxygenxml-incubator/oxygen-account pull request #50
Opened 2023-09-11 07:33 UTC by CostescuMarius

2023-09-11 10:12 UTC, balasaalin requested changes

2023-09-11 10:12 UTC, balasaalin commented on oxygen-account/src/main/resources/db/migration/V1_1__add_status_and_deletion_date_to_users.sql
> +ALTER TABLE users ADD COLUMN status VARCHAR(255) DEFAULT 'active' NOT NULL;
Renutam la valoarea default. Starea `active` va fi asignata la inregistrarea userului. (Pe viitor este posibil ca valoarea initiala sa se schimbe. Evitam astfel o noua migrare a bazei de date.)

2023-09-11 10:12 UTC, balasaalin commented on oxygen-account/src/main/resources/application.properties
> +spring.jpa.properties.hibernate.jdbc.time_zone = UTC
De verificat daca este neaparat nevoie de setarea asta?

2023-09-11 10:12 UTC, balasaalin commented on oxygen-account/src/test/resources/db/PopulateDatabase.sql
> +INSERT INTO users (name, email, password, registration_date) VALUES ('Denis Mateescu', 'denismateescu@gmail.com', '$2a$10$yWjIRyR/PQu2nS/0jzQa6.lj0YxI/Hc56fb/MD8rLteQe7kYn.NLS', CURRENT_TIMESTAMP());
Trebuie setat si statusul.

2023-09-13 07:56 UTC, adrianasbircea approved these changes

2023-09-13 07:57 UTC, merged